name: Check

on:
  push:
  pull_request:

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: cli/package-lock.json

      - name: Install JS dependencies
        run: npm ci --prefix cli

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run checks
        run: npm run check

      - name: Audit dependencies
        run: npm --prefix cli audit --audit-level=high

  macos-build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Build macOS app
        run: swift build
        working-directory: macos

  ios-build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Build iOS app
        run: >
          xcodebuild
          -project ios/WebFinder.xcodeproj
          -scheme WebFinder
          -destination 'generic/platform=iOS Simulator'
          -sdk iphonesimulator
          build
          CODE_SIGNING_ALLOWED=NO
